id: P003141
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016982
  title: ནག་ཆུའི་དམངས་ཁྲོད་གཏམ་དཔེ་མདོར་བསྡུས།
  author: ''
  volumes:
    ea8604fca73c440b9e452f5fdbd9152b:
      image_group_id: I00EGS1016998
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
